name: GH Runners Static Deployment
on: 
  workflow_dispatch:
    inputs:
      runner_count:
        description: "Number of Runners to Deploy"
        required: true
        default: 5

      runner_flavor:
        description: "The Flavor of VM to create. l3.nano (More Runners, Less Power) | l3.micro (Middle Ground) | l3.tiny (Less Runners, More Power)"
        required: true
        default: l3.nano

      image_name:
        description: "Name of image to create"
        required: true
        default: "static-gh-action-runner-image"
  
  push:
    branches:
      - CreateVMsWithGHActions

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: self-hosted-gh-runners/static/terraform
    outputs:
      vm_ips: ${{ steps.check-vms.outputs.vm-ips }}
    env:
      OS_CLIENT_CONFIG_FILE: ${{ github.workspace }}/clouds.yaml
      IMAGE_NAME: ${{ github.events.inputs.image_name }}
      FLAVOR_NAME: l3.nano
      TF_VAR_runner_count: 3 #${{ github.events.inputs.runner_count }}
      TF_VAR_flavor_name: l3.nano #${{ github.events.inputs.runner_flavor }}
      TF_VAR_floating_ip: ${{ secrets.UA_FLOATING_IP }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Create clouds.yaml
        run: echo "${{ secrets.OPENSTACK_CLOUDS }}" >> ${{ github.workspace }}/clouds.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
          terraform_wrapper: false
      
      - name: Setup vault
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan 1> /dev/null

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan 1> /dev/null

      - name: Create hosts.ini & Crete list of IPs
        id: check-vms
        run: |
          
          echo $(terraform output -json vm_ips) | jq -r '.[]' >> ../../playbooks/hosts.ini
          echo "vm_ips=$(echo $(terraform output -json vm_ips) | jq -r '.[]')" >> $GITHUB_OUTPUT
      
      - name: Put hosts.ini
        env:
          VM_IPS: ${{ steps.export.outputs.check-vms.vm_ips }}
        run: |
          vault login -address="${{ secrets.VAULT_URL }}" ${{ secrets.VAULT_TOKEN }} 1> /dev/null
          vault kv put -address="${{ secrets.VAULT_URL }}" -mount="fase-ci-cd" "static-hosts" static-hosts="$VM_IPS"

      - name: Put terraform.tfstate
        run: |
          vault login -address="${{ secrets.VAULT_URL }}" ${{ secrets.VAULT_TOKEN }} 1> /dev/null
          vault kv put -address="${{ secrets.VAULT_URL }}" -mount="fase-ci-cd" "static-tfstate" static-tfstate="@terraform.tfstate"

      - name: Setup SSH
        env:
          RUNNER_IPS: ${{ steps.export.outputs.check-vms.vm_ips }}
          ANISBLE_IP: ${{ secrets.UA_FLOATING_IP }}
          FASE_SSH_KEY: ${{ secrets.FASE_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo -e "$FASE_SSH_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          echo "$RUNNER_IPS" >> ../../playbooks/hosts.txt
          sed -i '$!s/$/,/' ../../playbooks/hosts.txt
          echo "$ANSIBLE_IP" >> ~/host.txt
          ssh-keyscan -f ~/host.txt >> ~/.ssh/known_hosts

      - name: Set Up Ansible VM
        env:
          VM_IP: ${{ secrets.UA_FLOATING_IP }}
        run: |
          scp -r ../../playbooks/ ubuntu@$VM_IP ~/playbooks
          ssh ubuntu@$VM_IP ssh-keyscan -f ~/playbooks/hosts.txt >> ~/.ssh/known_hosts

      - name: Run playbook on ansible VM
        env:
          VM_IP: ${{ secrets.UA_FLOATING_IP }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          ssh ubuntu@$VM_IP ansible-playbook ~/playbooks/ansible_install_github_actions_runner.yaml -i hosts.ini --private-key ~/.ssh/id_rsa --extra-vars="ACCESS_TOKEN=$ACCESS_TOKEN" --extra-vars="ORG=isisbusapps"